---
#- name: Install Java
#  hosts: kafka
#  roles:
#    - name: sansible.java
#      java:
#        version: 8

- name: Install Kafka Server
  hosts: kafka
  vars:
    kafka_internal_host: 10.164.0.18
    kafka_external_host: 35.204.253.91
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build
#        - configure
  roles:
    - name: sansible.zookeeper
    - name: sansible.kafka

# + restart sudo systemctl restart kafka
