---
- name: Install Postgres Server
  hosts: postgres
  become: yes
  vars:
    postgresql_global_config_options:
      - option: listen_addresses
        value: '*'
      - option: unix_socket_directories
        value: '{{ postgresql_unix_socket_directories | join(",") }}'
    postgresql_hba_entries:
      - {type: local, database: all, user: postgres, auth_method: peer}
      - {type: local, database: all, user: all, auth_method: peer}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
      - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
    postgresql_users:
      - name: ay
        password: secret_
    postgresql_databases:
      - name: test_db
        owner: ay

  roles:
    - geerlingguy.postgresql
