---
# https://galaxy.ansible.com/sansible/java
#- name: sansible.java
#  version: v2.1.3

# https://galaxy.ansible.com/sansible/users_and_groups
#- name: sansible.users_and_groups
#  version: v2.0.5

# https://galaxy.ansible.com/sansible/zookeeper
- name: sansible.zookeeper
  version: v3.2.6
# https://galaxy.ansible.com/sansible/kafka
- name: sansible.kafka
  version: v3.2.2

- src: geerlingguy.postgresql
  version: 2.0.0
